### ISSUE TITLE
Parsing {co}

### ISSUE THREAD

**Issue by tsani** [himikof/typed-lojban#1]
Hi, 
In the readme, I noticed this line:

``` haskell
reprTextTree $ untype $ tavla `tanruApp` pelxu `co` zdani
"(zdani co (tavla pelxu))"
```

This should parse as {(tavla pelxu) co zdani} which is equivalent to {zdani ke tavla pelxu [ke'e]}. {co} has the loosest scope of all the tanru grouping operators. It cannot even be contained in ke..ke'e brackets, e.g. {ke broda brode co brodi} has an elided {ke'e} before the {co}.

**Comment by himikof** [comment]
Well, actually this code performs the _reverse_ of parsing Lojban &mdash; it constructs a well-typed AST-like representation, and converts it by untyping to a Lojban text parse tree. But you have a valid point &mdash; I totally forgot to swap arguments of the `co` helper function, so the code, while performing a correct untyping, can only confuse Lojban readers. Thanks!
